@user1 = 9cda3624-54a9-4c08-8d29-c9d9fe585995
@user2 = 3e24bce7-48a4-4103-9a8f-179b38ddb41c

@host = http://localhost:8080
# @host = https://gardenpathapi.jasoncabot.me

### Create Game
# @name createGame
POST {{host}}/games
Content-Type: application/json
Authorization: Bearer {{user1}}

{
    "name": "Player 1",
    "colour": 512321,
    "numberOfPlayers": 2
}

### Player 2 - Join Game
# @name joinGame
POST {{host}}/games/{{createGame.response.body.code}}/players
Content-Type: application/json
Authorization: Bearer {{user2}}

{
    "name": "Player 2",
    "colour": 2
}

### Start Game as Player 1
# @name startGame1

POST {{host}}/games/{{createGame.response.body.id}}/turn
Content-Type: application/json
Authorization: Bearer {{user1}}

### Start Game as Player 2
# @name startGame2

POST {{host}}/games/{{createGame.response.body.id}}/turn
Content-Type: application/json
Authorization: Bearer {{user2}}

### Move as Player 1

POST {{host}}/games/{{createGame.response.body.id}}/move
Content-Type: application/json
Authorization: Bearer {{user1}}

{
    "position": 4
}

### Move as Player 2

POST {{host}}/games/{{createGame.response.body.id}}/move
Content-Type: application/json
Authorization: Bearer {{user2}}

{
    "position": 25
}

### Fence as Player 1

POST {{host}}/games/{{createGame.response.body.id}}/fence
Content-Type: application/json
Authorization: Bearer {{user1}}

{
    "start": 31,
    "end": 33
}

### Fence as Player 2

POST {{host}}/games/{{createGame.response.body.id}}/fence
Content-Type: application/json
Authorization: Bearer {{user2}}

{
    "start": 33,
    "end": 35
}

### View Game as Player 1

GET {{host}}/games/{{createGame.response.body.id}}
Content-Type: application/json
Authorization: Bearer {{user1}}


### View Game as Player 2

GET {{host}}/games/{{createGame.response.body.id}}
Content-Type: application/json
Authorization: Bearer {{user2}}
