@user1 = 9cda3624-54a9-4c08-8d29-c9d9fe585995
@user2 = 3e24bce7-48a4-4103-9a8f-179b38ddb41c
@createdGameId = bfec4e8f-1946-4d80-b210-8cd4c6391d0c

@host = http://localhost:8080
# @host = https://gardenpathapi.jasoncabot.me

### Create game

POST {{host}}/games
Content-Type: application/json
Authorization: Bearer {{user1}}

{
    "name": "Player 1",
    "numberOfPlayers": 2
}

### Player 2 - Join Game

POST {{host}}/games/{{createdGameId}}/players
Content-Type: application/json
Authorization: Bearer {{user2}}

{
    "name": "Player 2"
}

### Start Game as Player 1

POST {{host}}/games/{{createdGameId}}/turn
Content-Type: application/json
Authorization: Bearer {{user1}}

### Start Game as Player 2

POST {{host}}/games/{{createdGameId}}/turn
Content-Type: application/json
Authorization: Bearer {{user2}}

### Move as Player 1

POST {{host}}/games/{{createdGameId}}/move
Content-Type: application/json
Authorization: Bearer {{user1}}

{
    "position": 4
}

### Move as Player 2

POST {{host}}/games/{{createdGameId}}/move
Content-Type: application/json
Authorization: Bearer {{user2}}

{
    "position": 25
}

### Fence as Player 1

POST {{host}}/games/{{createdGameId}}/fence
Content-Type: application/json
Authorization: Bearer {{user1}}

{
    "start": 31,
    "end": 33
}

### Fence as Player 2

POST {{host}}/games/{{createdGameId}}/fence
Content-Type: application/json
Authorization: Bearer {{user2}}

{
    "start": 33,
    "end": 35
}

### View Game as Player 1

GET {{host}}/games/{{createdGameId}}
Content-Type: application/json
Authorization: Bearer {{user1}}


### View Game as Player 2

GET {{host}}/games/{{createdGameId}}
Content-Type: application/json
Authorization: Bearer {{user2}}
